import Nav from "@/app/common/Nav";
import Script from "next/script";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
        <html lang="ko">
        <head>
            <Script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" strategy="lazyOnload"></Script>
        </head>
        <body>
        <Nav/>
        <div className="container-fluid p-0">
            {children}
        </div>
        </body>
        </html>
  )
}
